---
- name: Install docker
  become: yes
  pacman:
    name: docker
    state: present
- name: Add user to docker
  user:
    name: "{{username}}"
    group: docker
    state: present
- name: Enable service docker
  service:
    name: docker
    enabled: yes
    state: started
- name: Install docker-compose
  become: yes
  pacman:
    name: docker-compose
    state: present
