---
- name: Install zsh
  become: yes
  pacman:
    name: zsh
    state: present
- name: Configure zsh as default shell
  shell: |
    chsh -s /bin/sh
- name: Install oh-my-zsh
  shell: |
    curl -s "https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh" | bash
- name: Install zinit
  shell: |
    curl -s "https://raw.githubusercontent.com/zdharma/zinit/master/doc/install.sh" | bash
- name: Install htop
  become: yes
  pacman:
    name: htop
    state: present
- name: Install autojump
  aur: name=autojump
  become: yes
  become_user: aur_builder
- name: Install mlocate
  become: yes
  pacman:
    name: mlocate
    state: present
- name: Install bat
  become: yes
  pacman:
    name: bat
    state: present
- name: Install fzf # fzf is a general-purpose command-line fuzzy finder.
  become: yes
  pacman:
    name: fzf
    state: present
- name: Install iftop
  become: yes
  pacman:
    name: iftop
    state: present
- name: Install jq
  become: yes
  pacman:
    name: jq
    state: present
- name: Install fd # https://github.com/sharkdp/fd
  become: yes
  pacman:
    name: fd
    state: present
- name: Copy .zshrc
  copy:
    src: .zshrc
    dest: "/home/{{username}}/.zshrc"
    backup: yes
    owner: "{{username}}"
